### PR TITLE
Fix the page routing

### PR DESCRIPTION
**Pull request by yijianwang**
Fix the issue that page routing like "/About" doesn't work.

### CODE REVIEW

**Comment by MMoudy49** [comment]
Page routing works on my machine. What issues were you seeing?

**Comment by yijianwang** [comment]
> Page routing works for the UI on my machine. What issues were you seeing?

Try localhost:8080/About directly and you will see the issue

**Comment by MMoudy49** [comment]
Ah got it. So it's with the server not the UI.

**Comment by yijianwang** [comment]
> Ah got it. So it's with the server not the UI.

yes, the UI code will eventually be served by server

**Pull request merged**
